# Enable ZMK Display
CONFIG_ZMK_DISPLAY=y

# Standard Widgets
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=n

# Use a dedicated work queue for the display
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# External power for OLED
CONFIG_ZMK_EXT_POWER=y

# Set sleep timeout to 30min (30*60*1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Enable mouse
CONFIG_ZMK_POINTING=y

# Bluetooth tweaks
CONFIG_ZMK_BLE=y
CONFIG_BT=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
# CONFIG_BT_CTLR_TX_PWR_PLUS_8 is currently removed to avoid Kconfig selection warnings
